/**
 * Project templates: deterministic starter-file generation for a controlled
 * set of application types. `generateFiles` is a PURE function of the
 * specification - no execution, no host access, no network, no credentials.
 *
 * Every template declares its own validation rules and test commands; the
 * generic engine never hard-codes structure assumptions.
 */

import { GenerationError } from '../errors/index.js';
import { type AppSpecification, type PlannedFile, type ProjectTemplate } from '../types/index.js';

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

export class TemplateRegistry {
  private readonly templates = new Map<string, ProjectTemplate>();

  register(template: ProjectTemplate): void {
    if (this.templates.has(template.id)) {
      throw new GenerationError(
        'GENERATION_UNSUPPORTED_TEMPLATE',
        'template id already registered',
        {
          templateId: template.id,
        },
      );
    }
    this.templates.set(template.id, template);
  }

  get(templateId: string): ProjectTemplate {
    const template = this.templates.get(templateId);
    if (template === undefined) {
      throw new GenerationError(
        'GENERATION_UNSUPPORTED_TEMPLATE',
        `unknown template "${templateId}"`,
        {
          templateId,
        },
      );
    }
    return template;
  }

  list(): readonly ProjectTemplate[] {
    return [...this.templates.values()];
  }
}

// ---------------------------------------------------------------------------
// Content helpers (pure, deterministic)
// ---------------------------------------------------------------------------

function pascalCase(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9]+/g, ' ').trim();
  return cleaned
    .split(' ')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function slugName(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 64) || 'generated-app'
  );
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function screenComponents(spec: AppSpecification): readonly PlannedFile[] {
  if (spec.screens.length === 0) return [];
  return spec.screens.map((screen) => {
    const componentName = pascalCase(screen.name);
    return {
      path: `src/pages/${componentName}.tsx`,
      content: [
        `/**`,
        ` * ${componentName} - generated by Veltravia AI.`,
        ` * ${screen.description ?? screen.name}`,
        ` */`,
        `export default function ${componentName}() {`,
        `  return (`,
        `    <section aria-label="${escapeHtml(screen.name)}">`,
        `      <h2>${escapeHtml(screen.name)}</h2>`,
        `      <p>${escapeHtml(screen.description ?? `The ${screen.name} screen.`)}</p>`,
        `    </section>`,
        `  );`,
        `}`,
        ``,
      ].join('\n'),
    };
  });
}

function appShell(spec: AppSpecification): string {
  const nav = spec.screens
    .map(
      (screen) =>
        `        <li><a href="#${slugName(screen.name)}">${escapeHtml(screen.name)}</a></li>`,
    )
    .join('\n');
  return [
    `/**`,
    ` * ${escapeHtml(spec.name)} - generated by Veltravia AI.`,
    ` * ${escapeHtml(spec.description)}`,
    ` */`,
    ...(spec.features.length > 0
      ? [`// Planned features: ${spec.features.map((feature) => feature).join('; ')}`]
      : []),
    ...(spec.entities.length > 0
      ? ['// Planned entities: ' + spec.entities.map((entity) => entity.name).join(', ')]
      : []),
    ``,
    `export default function App() {`,
    `  return (`,
    `    <main>`,
    `      <h1>${escapeHtml(spec.name)}</h1>`,
    `      <p>${escapeHtml(spec.description)}</p>`,
    ...(spec.screens.length > 0
      ? [`      <nav aria-label="Screens">`, `        <ul>`, nav, `        </ul>`, `      </nav>`]
      : []),
    `    </main>`,
    `  );`,
    `}`,
    ``,
  ]
    .filter((line) => line !== undefined)
    .join('\n');
}

function packageJson(spec: AppSpecification, extraScripts: Record<string, string>): string {
  const scripts: Record<string, string> = {
    dev: 'vite',
    build: 'tsc && vite build',
    preview: 'vite preview',
    ...extraScripts,
  };
  return `${JSON.stringify(
    {
      name: slugName(spec.name),
      version: spec.version,
      private: true,
      type: 'module',
      scripts,
      dependencies: {
        react: '^18.3.1',
        'react-dom': '^18.3.1',
      },
      devDependencies: {
        '@types/react': '^18.3.12',
        '@types/react-dom': '^18.3.1',
        '@vitejs/plugin-react': '^4.3.4',
        typescript: '^5.6.3',
        vite: '^5.4.11',
      },
    },
    null,
    2,
  )}\n`;
}

// ---------------------------------------------------------------------------
// web-react template
// ---------------------------------------------------------------------------

export const WEB_REACT_TEMPLATE: ProjectTemplate = {
  id: 'web-react',
  name: 'React Web Application',
  version: '1.0.0',
  description: 'A deterministic React 18 + TypeScript + Vite single-page web application skeleton.',
  supportedAppTypes: ['web'],
  technologyStack: {
    frontend: 'React 18 + TypeScript',
    buildTool: 'Vite 5',
    language: 'TypeScript 5',
  },
  requiredDependencies: ['react', 'react-dom'],
  validationRules: {
    requiredFiles: ['package.json', 'index.html', 'src/main.tsx', 'src/App.tsx'],
    requiredDirectories: ['src'],
    packageManifestRequired: true,
  },
  testCommands: [
    {
      command: 'node',
      arguments: ['--version'],
      purpose: 'Verify the Node.js runtime is available.',
    },
  ],
  generateFiles(spec) {
    return [
      { path: 'package.json', content: packageJson(spec, {}) },
      {
        path: 'index.html',
        content: [
          `<!doctype html>`,
          `<html lang="en">`,
          `  <head>`,
          `    <meta charset="UTF-8" />`,
          `    <meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
          `    <title>${escapeHtml(spec.name)}</title>`,
          `  </head>`,
          `  <body>`,
          `    <div id="root"></div>`,
          `    <script type="module" src="/src/main.tsx"></script>`,
          `  </body>`,
          `</html>`,
          ``,
        ].join('\n'),
      },
      {
        path: 'vite.config.ts',
        content: [
          `import react from '@vitejs/plugin-react';`,
          ``,
          `export default {`,
          `  plugins: [react()],`,
          `};`,
          ``,
        ].join('\n'),
      },
      {
        path: 'tsconfig.json',
        content: `${JSON.stringify(
          {
            compilerOptions: {
              target: 'ES2022',
              lib: ['ES2022', 'DOM', 'DOM.Iterable'],
              module: 'ESNext',
              moduleResolution: 'bundler',
              jsx: 'react-jsx',
              strict: true,
              noEmit: true,
              skipLibCheck: true,
            },
            include: ['src'],
          },
          null,
          2,
        )}\n`,
      },
      {
        path: 'src/main.tsx',
        content: [
          `import { StrictMode } from 'react';`,
          `import { createRoot } from 'react-dom/client';`,
          ``,
          `import App from './App';`,
          ``,
          `createRoot(document.getElementById('root') as HTMLElement).render(`,
          `  <StrictMode>`,
          `    <App />`,
          `  </StrictMode>,`,
          `);`,
          ``,
        ].join('\n'),
      },
      { path: 'src/App.tsx', content: appShell(spec) },
      ...screenComponents(spec),
      {
        path: 'README.md',
        content: [
          `# ${spec.name}`,
          ``,
          `${spec.description}`,
          ``,
          `Generated by Veltravia AI. Development: \`npm run dev\`.`,
          ``,
        ].join('\n'),
      },
    ];
  },
};

// ---------------------------------------------------------------------------
// fullstack-react-fastify template
// ---------------------------------------------------------------------------

const SERVER_APP = [
  `import Fastify from 'fastify';`,
  ``,
  `/** Generated by Veltravia AI. */`,
  `const app = Fastify({ logger: false });`,
  ``,
  `app.get('/health', async () => ({ status: 'ok' }));`,
  ``,
  `app.listen({ port: 3000, host: '0.0.0.0' });`,
  ``,
].join('\n');

export const FULLSTACK_REACT_FASTIFY_TEMPLATE: ProjectTemplate = {
  id: 'fullstack-react-fastify',
  name: 'React + Fastify Full-Stack Application',
  version: '1.0.0',
  description:
    'A deterministic full-stack skeleton: React 18 + Vite frontend plus a Fastify API server, in one project.',
  supportedAppTypes: ['fullstack'],
  technologyStack: {
    frontend: 'React 18 + TypeScript',
    backend: 'Fastify 4 + TypeScript',
    buildTool: 'Vite 5',
    language: 'TypeScript 5',
  },
  requiredDependencies: ['react', 'react-dom', 'fastify'],
  validationRules: {
    requiredFiles: ['package.json', 'index.html', 'src/main.tsx', 'src/App.tsx', 'server/index.ts'],
    requiredDirectories: ['src', 'server'],
    packageManifestRequired: true,
  },
  testCommands: [
    {
      command: 'node',
      arguments: ['--version'],
      purpose: 'Verify the Node.js runtime is available.',
    },
    {
      command: 'node',
      arguments: ['--check', 'server/index.ts'],
      purpose: 'Syntax-check the API server entry file.',
    },
  ],
  generateFiles(spec) {
    return [
      {
        path: 'package.json',
        content: packageJson(spec, {
          'start:server': 'node server/index.ts',
        }).replace('"dependencies": {', '"dependencies": {\n    "fastify": "^4.28.1",'),
      },
      ...WEB_REACT_TEMPLATE.generateFiles(spec).filter((file) => file.path !== 'package.json'),
      { path: 'server/index.ts', content: SERVER_APP },
    ];
  },
};

/** The built-in template set, honestly limited to what is implemented. */
export function createDefaultTemplateRegistry(): TemplateRegistry {
  const registry = new TemplateRegistry();
  registry.register(WEB_REACT_TEMPLATE);
  registry.register(FULLSTACK_REACT_FASTIFY_TEMPLATE);
  return registry;
}
